// This file is auto-generated by @tanstack/router-plugin
// It will be regenerated when you run the dev server or build

import { RootRoute, Route } from "@tanstack/react-router";
import { Route as RootComponent } from "./routes/__root";
import { Route as IndexComponent } from "./routes/index";
import { Route as DecisionTreeComponent } from "./routes/decision-tree";

const RootRoute_ = new RootRoute({
  component: RootComponent.component,
  errorComponent: RootComponent.errorComponent,
  notFoundComponent: RootComponent.notFoundComponent,
  context: RootComponent.context,
});

const indexRoute = new Route({
  getParentRoute: () => RootRoute_,
  path: "/",
  component: IndexComponent.component,
});

const decisionTreeRoute = new Route({
  getParentRoute: () => RootRoute_,
  path: "/decision-tree",
  component: DecisionTreeComponent.component,
});

export const routeTree = RootRoute_.addChildren([indexRoute, decisionTreeRoute]);

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof routeTree;
  }
}
